const CARD_WIDTH = 920;
const CARD_HEIGHT = 1060;
const FONT_FAMILY = "Inter, Segoe UI, Arial, sans-serif";
const BACKGROUND = "#130F1E";
const SURFACE = "#1D182B";
const SURFACE_ALT = "#171322";
const TEXT = "#F7F1E8";
const MUTED = "#B8AB9D";
const LINE = "#3D344F";
const ACCENTS = ["#FFB86B", "#7EE7C8", "#FF6F91", "#A48CFF", "#F7E967"];

export function renderMarkdown(insights) {
  const repoRows = insights.recentRepos
    .map((repo) => {
      const description = repo.description
        ? escapeMarkdown(repo.description)
        : "No description provided.";
      return `| [${escapeMarkdown(repo.name)}](${repo.url}) | ${description} | ${repo.language ?? "n/a"} | ${repo.stars} | ${repo.forks} |`;
    })
    .join("\n");

  const languages =
    insights.topLanguages
      .map((item) => `${item.name} (${item.count})`)
      .join(", ") || "No language data yet";
  const topics =
    insights.topTopics.map((item) => `\`${item.name}\``).join(" ") ||
    "No topics yet";

  return [
    `<!-- repo-insight-card:start -->`,
    `## GitHub Insight Card`,
    ``,
    `This section is generated by **Repo Insight Card**, a real GitHub REST API integration.`,
    ``,
    `![GitHub Insight Card](./dist/profile-card.svg)`,
    ``,
    `Generated: ${insights.generatedAt}`,
    ``,
    `| Metric | Value |`,
    `| --- | ---: |`,
    `| Public repositories analyzed | ${insights.totals.repositories} |`,
    `| Source repositories | ${insights.totals.sourceRepositories} |`,
    `| Stars | ${insights.totals.stars} |`,
    `| Forks | ${insights.totals.forks} |`,
    `| Open issues | ${insights.totals.openIssues} |`,
    `| Followers | ${insights.profile.followers} |`,
    ``,
    `**Top languages:** ${languages}`,
    ``,
    `**Top topics:** ${topics}`,
    ``,
    `| Recently updated repositories | Description | Language | Stars | Forks |`,
    `| --- | --- | --- | ---: | ---: |`,
    repoRows || `| n/a | No repositories found. | n/a | 0 | 0 |`,
    `<!-- repo-insight-card:end -->`,
  ].join("\n");
}

export function renderSvg(insights) {
  const owner = insights.profile.name || insights.profile.login;
  const displayName = owner;
  const activity =
    insights.charts?.repositoryActivity ??
    monthlyRepositoryActivity(insights.recentRepos, insights.generatedAt);
  const languages = insights.charts?.languagesByRepo ?? insights.topLanguages;
  const recentRepos = insights.recentRepos.slice(0, 4);

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${CARD_WIDTH}" height="${CARD_HEIGHT}" viewBox="0 0 ${CARD_WIDTH} ${CARD_HEIGHT}" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">GitHub insight report for ${escapeXml(owner)}</title>
  <desc id="desc">A stacked repository insight report generated with the GitHub REST API.</desc>
  ${svgAnimationStyles()}
  <rect width="${CARD_WIDTH}" height="${CARD_HEIGHT}" rx="18" fill="${BACKGROUND}"/>
  ${decorativeGesture("top")}

  <g class="section section-profile">
    ${sectionHeader(126, "profile", "Identity")}
    <text x="36" y="164" fill="${TEXT}" font-family="${FONT_FAMILY}" font-size="36" font-weight="800">${escapeXml(displayName)}</text>
    <text x="36" y="196" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="14">Generated with Repo Insight Card and the GitHub REST API</text>
    <text x="704" y="154" fill="${ACCENTS[0]}" font-family="${FONT_FAMILY}" font-size="14" font-weight="700">updated</text>
    <text x="704" y="180" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="13">${escapeXml(formatShortDate(insights.generatedAt))}</text>
    ${divider(226)}
  </g>

  <g class="section section-signal">
    ${sectionHeader(266, "signal", "Core Signals")}
    ${metricTile(36, 294, "Repositories", insights.totals.repositories, ACCENTS[0])}
    ${metricTile(212, 294, "Stars", insights.totals.stars, ACCENTS[1])}
    ${metricTile(388, 294, "Forks", insights.totals.forks, ACCENTS[2])}
    ${metricTile(564, 294, "Followers", insights.profile.followers, ACCENTS[3])}
    ${metricTile(740, 294, "Open Issues", insights.totals.openIssues, ACCENTS[4])}
    ${divider(386)}
  </g>

  <g class="section section-activity">
    ${sectionHeader(426, "activity", "Repository Activity")}
    ${lineChart(236, 444, 630, 118, activity)}
    <text x="36" y="478" fill="${TEXT}" font-family="${FONT_FAMILY}" font-size="44" font-weight="800">${sumActivity(activity)}</text>
    <text x="36" y="506" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="13">repo updates tracked</text>
    <text x="36" y="532" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="13">${escapeXml(formatJoined(insights.profile.joinedAt, insights.generatedAt))}</text>
    <text x="36" y="558" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="13">${escapeXml(insights.profile.email || "Email private")}</text>
    ${divider(600)}
  </g>

  <g class="section section-language">
    ${sectionHeader(640, "language", "Language Shape")}
    ${languageBars(36, 672, 382, languages)}
    ${donutChart(766, 718, 70, 22, languages)}
    <text x="660" y="814" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="13">Top languages by repository count</text>
    ${divider(838)}
  </g>

  <g class="section section-recent">
    ${sectionHeader(874, "recent", "Recent Repositories")}
    ${repoStrip(36, 900, recentRepos)}
    ${divider(972)}
  </g>

  ${decorativeGesture("bottom")}
</svg>
`;
}

function svgAnimationStyles() {
  return `<style>
    .gesture-top {
      animation: driftTop 8s ease-in-out infinite alternate;
      transform-origin: 50% 0%;
    }
    .gesture-bottom {
      animation: driftBottom 9s ease-in-out infinite alternate;
      transform-origin: 50% 100%;
    }
    .gesture-glow {
      animation: breathe 5s ease-in-out infinite alternate;
    }
    .section {
      animation: settle 700ms ease both;
    }
    .section-profile { animation-delay: 80ms; }
    .section-signal { animation-delay: 180ms; }
    .section-activity { animation-delay: 280ms; }
    .section-language { animation-delay: 380ms; }
    .section-recent { animation-delay: 480ms; }
    .metric-tile {
      animation: tileLift 4s ease-in-out infinite alternate;
      transform-box: fill-box;
      transform-origin: center;
    }
    .chart-line {
      stroke-dasharray: 1200;
      stroke-dashoffset: 1200;
      animation: drawLine 1.4s ease 500ms forwards;
    }
    .chart-dot {
      animation: pulseDot 2.6s ease-in-out infinite;
      transform-box: fill-box;
      transform-origin: center;
    }
    .bar-fill {
      animation: barBreathe 3.2s ease-in-out infinite alternate;
      transform-box: fill-box;
      transform-origin: left center;
    }
    .donut-slice {
      animation: ringGlow 3.8s ease-in-out infinite alternate;
    }
    @keyframes driftTop {
      from { transform: translateX(-8px) translateY(0); opacity: 0.86; }
      to { transform: translateX(8px) translateY(10px); opacity: 1; }
    }
    @keyframes driftBottom {
      from { transform: translateX(8px) translateY(4px); opacity: 0.82; }
      to { transform: translateX(-10px) translateY(-8px); opacity: 1; }
    }
    @keyframes breathe {
      from { opacity: 0.18; }
      to { opacity: 0.46; }
    }
    @keyframes settle {
      from { opacity: 0; transform: translateY(12px); }
      to { opacity: 1; transform: translateY(0); }
    }
    @keyframes tileLift {
      from { transform: translateY(0); }
      to { transform: translateY(-3px); }
    }
    @keyframes drawLine {
      to { stroke-dashoffset: 0; }
    }
    @keyframes pulseDot {
      0%, 100% { transform: scale(1); opacity: 0.86; }
      50% { transform: scale(1.45); opacity: 1; }
    }
    @keyframes barBreathe {
      from { opacity: 0.78; }
      to { opacity: 1; }
    }
    @keyframes ringGlow {
      from { opacity: 0.74; }
      to { opacity: 1; }
    }
  </style>`;
}

function decorativeGesture(position) {
  if (position === "top") {
    return `<g class="gesture-top" aria-hidden="true">
      <path d="M -18 92 C 130 42, 250 118, 414 82 S 706 26, 944 80 V 0 H -18 Z" fill="#241A34"/>
      <path class="gesture-glow" d="M 18 82 C 176 40, 284 96, 436 70 S 700 42, 902 62" stroke="${ACCENTS[1]}" stroke-width="3" stroke-linecap="round"/>
    </g>`;
  }

  return `<g class="gesture-bottom" aria-hidden="true">
    <path d="M -20 ${CARD_HEIGHT} C 168 998, 304 1054, 458 1012 S 746 988, 942 1024 V ${CARD_HEIGHT} Z" fill="#211A2D"/>
    <path class="gesture-glow" d="M 28 1026 C 198 988, 310 1038, 470 1002 S 734 984, 894 1008" stroke="${ACCENTS[2]}" stroke-width="3" stroke-linecap="round"/>
  </g>`;
}

function sectionHeader(y, label, title) {
  return `<g>
    <text x="36" y="${y}" fill="${ACCENTS[0]}" font-family="${FONT_FAMILY}" font-size="11" font-weight="800" letter-spacing="2">${escapeXml(label.toUpperCase())}</text>
    <text x="128" y="${y}" fill="${TEXT}" font-family="${FONT_FAMILY}" font-size="17" font-weight="700">${escapeXml(title)}</text>
  </g>`;
}

function divider(y) {
  return `<g>
    <line x1="36" y1="${y}" x2="884" y2="${y}" stroke="${LINE}" stroke-width="1"/>
    <line x1="36" y1="${y}" x2="174" y2="${y}" stroke="${ACCENTS[0]}" stroke-width="3"/>
  </g>`;
}

function metricTile(x, y, label, value, color) {
  return `<g class="metric-tile">
    <rect x="${x}" y="${y}" width="138" height="58" rx="14" fill="${SURFACE}"/>
    <rect x="${x}" y="${y}" width="5" height="58" rx="2.5" fill="${color}"/>
    <text x="${x + 18}" y="${y + 24}" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="12">${escapeXml(label)}</text>
    <text x="${x + 18}" y="${y + 50}" fill="${TEXT}" font-family="${FONT_FAMILY}" font-size="26" font-weight="800">${escapeXml(value)}</text>
  </g>`;
}

function lineChart(x, y, width, height, points) {
  const values = points.length ? points.map((point) => point.count) : [0];
  const maxValue = Math.max(1, ...values);
  const plotPoints = points.length
    ? points.map((point, index) => {
        const px = x + (index / Math.max(1, points.length - 1)) * width;
        const py = y + height - (point.count / maxValue) * height;
        return { ...point, x: px, y: py };
      })
    : [{ x, y: y + height, label: "", count: 0 }];
  const line = plotPoints
    .map((point) => `${point.x.toFixed(1)},${point.y.toFixed(1)}`)
    .join(" ");
  const area = `${x},${y + height} ${line} ${x + width},${y + height}`;
  const labels = plotPoints.filter(
    (_, index) => index % 2 === 0 || index === plotPoints.length - 1,
  );

  return `<g>
    <rect x="${x}" y="${y}" width="${width}" height="${height}" rx="12" fill="${SURFACE_ALT}"/>
    ${Array.from({ length: 4 }, (_, index) => {
      const gy = y + 22 + index * 26;
      return `<line x1="${x + 18}" y1="${gy}" x2="${x + width - 18}" y2="${gy}" stroke="${LINE}" stroke-width="1"/>`;
    }).join("")}
    <polygon points="${area}" fill="${ACCENTS[1]}" opacity="0.2"/>
    <polyline class="chart-line" points="${line}" fill="none" stroke="${ACCENTS[1]}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
    ${plotPoints.map((point, index) => `<circle class="chart-dot" style="animation-delay: ${index * 90}ms" cx="${point.x}" cy="${point.y}" r="3.5" fill="${ACCENTS[0]}"/>`).join("")}
    ${labels
      .map(
        (point) =>
          `<text x="${point.x - 16}" y="${y + height + 20}" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="11">${escapeXml(point.label)}</text>`,
      )
      .join("")}
  </g>`;
}

function languageBars(x, y, width, items) {
  if (!items.length) {
    return `<text x="${x}" y="${y}" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="14">No language data yet</text>`;
  }

  const maxValue = Math.max(...items.map((item) => item.count), 1);

  return `<g>${items
    .map((item, index) => {
      const rowY = y + index * 31;
      const barWidth = Math.max(18, (item.count / maxValue) * width);
      const color = ACCENTS[index % ACCENTS.length];
      return `<g>
        <text x="${x}" y="${rowY}" fill="${TEXT}" font-family="${FONT_FAMILY}" font-size="14" font-weight="700">${escapeXml(item.name)}</text>
        <text x="${x + 132}" y="${rowY}" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="13">${escapeXml(item.count)}</text>
        <rect x="${x + 166}" y="${rowY - 12}" width="${width}" height="10" rx="5" fill="${SURFACE_ALT}"/>
        <rect class="bar-fill" x="${x + 166}" y="${rowY - 12}" width="${barWidth}" height="10" rx="5" fill="${color}"/>
      </g>`;
    })
    .join("")}</g>`;
}

function donutChart(cx, cy, radius, strokeWidth, items) {
  const total = items.reduce((sum, item) => sum + item.count, 0);

  if (!total) {
    return `<circle cx="${cx}" cy="${cy}" r="${radius}" fill="none" stroke="${LINE}" stroke-width="${strokeWidth}"/>`;
  }

  let start = -90;
  const slices = items
    .map((item, index) => {
      const angle = (item.count / total) * 360;
      const slice = arc(cx, cy, radius, start, start + angle);
      start += angle;
      return `<path class="donut-slice" d="${slice}" fill="none" stroke="${ACCENTS[index % ACCENTS.length]}" stroke-width="${strokeWidth}" stroke-linecap="butt"/>`;
    })
    .join("");

  return `<g>
    <circle cx="${cx}" cy="${cy}" r="${radius}" fill="none" stroke="${SURFACE_ALT}" stroke-width="${strokeWidth}"/>
    ${slices}
    <circle cx="${cx}" cy="${cy}" r="${radius - strokeWidth / 2 - 3}" fill="${BACKGROUND}"/>
    <text x="${cx}" y="${cy - 2}" text-anchor="middle" fill="${TEXT}" font-family="${FONT_FAMILY}" font-size="28" font-weight="800">${total}</text>
    <text x="${cx}" y="${cy + 20}" text-anchor="middle" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="11">repos</text>
  </g>`;
}

function repoStrip(x, y, repos) {
  if (!repos.length) {
    return `<text x="${x}" y="${y + 22}" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="14">No repositories found.</text>`;
  }

  return `<g>${repos
    .map((repo, index) => {
      const rx = x + index * 216;
      const color = ACCENTS[index % ACCENTS.length];
      return `<g class="metric-tile">
        <rect x="${rx}" y="${y}" width="198" height="48" rx="12" fill="${SURFACE}"/>
        <rect x="${rx}" y="${y}" width="4" height="48" rx="2" fill="${color}"/>
        <circle cx="${rx + 22}" cy="${y + 24}" r="5" fill="${color}"/>
        <text x="${rx + 38}" y="${y + 22}" fill="${TEXT}" font-family="${FONT_FAMILY}" font-size="12" font-weight="800">${escapeXml(truncate(repo.name, 19))}</text>
        <text x="${rx + 38}" y="${y + 38}" fill="${MUTED}" font-family="${FONT_FAMILY}" font-size="11">${escapeXml(repo.language || "Language n/a")}</text>
      </g>`;
    })
    .join("")}</g>`;
}

function arc(cx, cy, radius, startAngle, endAngle) {
  const start = polarToCartesian(cx, cy, radius, endAngle);
  const end = polarToCartesian(cx, cy, radius, startAngle);
  const largeArcFlag = endAngle - startAngle <= 180 ? "0" : "1";

  return `M ${start.x} ${start.y} A ${radius} ${radius} 0 ${largeArcFlag} 0 ${end.x} ${end.y}`;
}

function polarToCartesian(cx, cy, radius, angleInDegrees) {
  const angleInRadians = ((angleInDegrees - 90) * Math.PI) / 180;

  return {
    x: Number((cx + radius * Math.cos(angleInRadians)).toFixed(3)),
    y: Number((cy + radius * Math.sin(angleInRadians)).toFixed(3)),
  };
}

function formatJoined(joinedAt, generatedAt) {
  if (!joinedAt) {
    return "GitHub join date unavailable";
  }

  const joined = new Date(joinedAt);
  const generated = new Date(generatedAt);
  const years = Math.max(
    0,
    generated.getUTCFullYear() -
      joined.getUTCFullYear() -
      (generated.getUTCMonth() < joined.getUTCMonth() ||
      (generated.getUTCMonth() === joined.getUTCMonth() &&
        generated.getUTCDate() < joined.getUTCDate())
        ? 1
        : 0),
  );

  if (years === 0) {
    return "Joined GitHub less than a year ago";
  }

  return `Joined GitHub ${years} ${years === 1 ? "year" : "years"} ago`;
}

function formatShortDate(value) {
  return new Date(value).toISOString().slice(0, 10);
}

function sumActivity(activity) {
  return activity.reduce((sum, item) => sum + item.count, 0);
}

function monthlyRepositoryActivity(repositories, generatedAt) {
  const end = new Date(generatedAt);
  const months = [];

  for (let offset = 11; offset >= 0; offset -= 1) {
    const date = new Date(
      Date.UTC(end.getUTCFullYear(), end.getUTCMonth() - offset, 1),
    );
    months.push({
      key: `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`,
      label: `${String(date.getUTCFullYear()).slice(2)}/${String(date.getUTCMonth() + 1).padStart(2, "0")}`,
      count: 0,
    });
  }

  const indexByKey = new Map(months.map((month, index) => [month.key, index]));

  for (const repo of repositories ?? []) {
    const updatedAt = repo.updatedAt ?? repo.updated_at;

    if (!updatedAt) {
      continue;
    }

    const updated = new Date(updatedAt);
    const key = `${updated.getUTCFullYear()}-${String(updated.getUTCMonth() + 1).padStart(2, "0")}`;
    const index = indexByKey.get(key);

    if (index !== undefined) {
      months[index].count += 1;
    }
  }

  return months;
}

function truncate(value, maxLength) {
  const text = String(value);

  if (text.length <= maxLength) {
    return text;
  }

  return `${text.slice(0, maxLength - 1)}...`;
}

function escapeMarkdown(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}
