const CARD_WIDTH = 840;
const CARD_HEIGHT = 360;

export function renderMarkdown(insights) {
  const repoRows = insights.recentRepos
    .map((repo) => {
      const description = repo.description
        ? escapeMarkdown(repo.description)
        : "No description provided.";
      return `| [${escapeMarkdown(repo.name)}](${repo.url}) | ${description} | ${repo.language ?? "n/a"} | ${repo.stars} | ${repo.forks} |`;
    })
    .join("\n");

  const languages =
    insights.topLanguages
      .map((item) => `${item.name} (${item.count})`)
      .join(", ") || "No language data yet";
  const topics =
    insights.topTopics.map((item) => `\`${item.name}\``).join(" ") ||
    "No topics yet";

  return [
    `<!-- repo-insight-card:start -->`,
    `## GitHub Insight Card`,
    ``,
    `This section is generated by **Repo Insight Card**, a real GitHub REST API integration.`,
    ``,
    `![GitHub Insight Card](./dist/profile-card.svg)`,
    ``,
    `Generated: ${insights.generatedAt}`,
    ``,
    `| Metric | Value |`,
    `| --- | ---: |`,
    `| Public repositories analyzed | ${insights.totals.repositories} |`,
    `| Source repositories | ${insights.totals.sourceRepositories} |`,
    `| Stars | ${insights.totals.stars} |`,
    `| Forks | ${insights.totals.forks} |`,
    `| Open issues | ${insights.totals.openIssues} |`,
    `| Followers | ${insights.profile.followers} |`,
    ``,
    `**Top languages:** ${languages}`,
    ``,
    `**Top topics:** ${topics}`,
    ``,
    `| Recently updated repositories | Description | Language | Stars | Forks |`,
    `| --- | --- | --- | ---: | ---: |`,
    repoRows || `| n/a | No repositories found. | n/a | 0 | 0 |`,
    `<!-- repo-insight-card:end -->`,
  ].join("\n");
}

export function renderSvg(insights) {
  const languageText =
    insights.topLanguages
      .map((item) => `${item.name} ${item.count}`)
      .join("  /  ") || "No language data yet";
  const owner = insights.profile.name || insights.profile.login;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${CARD_WIDTH}" height="${CARD_HEIGHT}" viewBox="0 0 ${CARD_WIDTH} ${CARD_HEIGHT}" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">GitHub insight card for ${escapeXml(owner)}</title>
  <desc id="desc">Generated repository statistics using the GitHub REST API.</desc>
  <rect width="${CARD_WIDTH}" height="${CARD_HEIGHT}" rx="8" fill="#0D1117"/>
  <rect x="24" y="24" width="792" height="312" rx="8" fill="#161B22" stroke="#30363D"/>
  <text x="48" y="70" fill="#F0F6FC" font-family="Arial, sans-serif" font-size="28" font-weight="700">${escapeXml(owner)}</text>
  <text x="48" y="102" fill="#8B949E" font-family="Arial, sans-serif" font-size="15">Generated with Repo Insight Card and the GitHub REST API</text>
  ${metric(48, 158, "Repositories", insights.totals.repositories)}
  ${metric(220, 158, "Stars", insights.totals.stars)}
  ${metric(392, 158, "Forks", insights.totals.forks)}
  ${metric(564, 158, "Followers", insights.profile.followers)}
  <text x="48" y="252" fill="#F0F6FC" font-family="Arial, sans-serif" font-size="17" font-weight="700">Top languages</text>
  <text x="48" y="284" fill="#C9D1D9" font-family="Arial, sans-serif" font-size="16">${escapeXml(languageText)}</text>
  <text x="48" y="316" fill="#8B949E" font-family="Arial, sans-serif" font-size="13">Updated ${escapeXml(insights.generatedAt)}</text>
</svg>
`;
}

function metric(x, y, label, value) {
  return `<g>
    <text x="${x}" y="${y}" fill="#F0F6FC" font-family="Arial, sans-serif" font-size="30" font-weight="700">${value}</text>
    <text x="${x}" y="${y + 28}" fill="#8B949E" font-family="Arial, sans-serif" font-size="14">${label}</text>
  </g>`;
}

function escapeMarkdown(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}
